apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static
spec:
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: portal-hostname:3260
     iqn: iqn
     lun: 0
     fsType: 'ext4'
     readOnly: false
